version: '3'
services:
  mongo:
    image: tutum/mongodb
    ports:
      - 27017:27017
      - 28017:28017

  sender:
    build: sender
    depends_on: 
      - mongo
      - redis

  subscriber:
    build: subscriber
    depends_on: 
      - mongo
      - redis

  redis:
    image: redis
    container_name: redis


